<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\Calendar;

use Atlas\Table\Row;

/**
 * @property mixed $service_id TEXT
 * @property mixed $monday TEXT
 * @property mixed $tuesday TEXT
 * @property mixed $wednesday TEXT
 * @property mixed $thursday TEXT
 * @property mixed $friday TEXT
 * @property mixed $saturday TEXT
 * @property mixed $sunday TEXT
 * @property mixed $start_date TEXT
 * @property mixed $end_date TEXT
 */
class CalendarRow extends Row
{
    protected $cols = [
        'service_id' => null,
        'monday' => null,
        'tuesday' => null,
        'wednesday' => null,
        'thursday' => null,
        'friday' => null,
        'saturday' => null,
        'sunday' => null,
        'start_date' => null,
        'end_date' => null,
    ];
}
