<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\Calendar;

/**
 * @property mixed $service_id TEXT
 * @property mixed $monday TEXT
 * @property mixed $tuesday TEXT
 * @property mixed $wednesday TEXT
 * @property mixed $thursday TEXT
 * @property mixed $friday TEXT
 * @property mixed $saturday TEXT
 * @property mixed $sunday TEXT
 * @property mixed $start_date TEXT
 * @property mixed $end_date TEXT
 */
trait CalendarFields
{
}
