<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\FareRule;

/**
 * @property mixed $fare_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $origin_id TEXT
 * @property mixed $destination_id TEXT
 * @property mixed $contains_id TEXT
 */
trait FareRuleFields
{
}
