<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\FareRule;

use Atlas\Table\Row;

/**
 * @property mixed $fare_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $origin_id TEXT
 * @property mixed $destination_id TEXT
 * @property mixed $contains_id TEXT
 */
class FareRuleRow extends Row
{
    protected $cols = [
        'fare_id' => null,
        'route_id' => null,
        'origin_id' => null,
        'destination_id' => null,
        'contains_id' => null,
    ];
}
