<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Level;

/**
 * @property mixed $level_id TEXT
 * @property mixed $level_index REAL
 * @property mixed $level_name TEXT
 */
trait LevelFields
{
}
