<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Trip;

/**
 * @property mixed $route_id TEXT
 * @property mixed $service_id TEXT
 * @property mixed $trip_id TEXT
 * @property mixed $trip_headsign TEXT
 * @property mixed $trip_short_name TEXT
 * @property mixed $direction_id TEXT
 * @property mixed $block_id TEXT
 * @property mixed $shape_id TEXT
 * @property mixed $wheelchair_accessible TEXT
 * @property mixed $bikes_allowed TEXT
 */
trait TripFields
{
}
