<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\FareAttribute;

use Atlas\Table\Row;

/**
 * @property mixed $fare_id TEXT
 * @property mixed $price REAL
 * @property mixed $currency_type TEXT
 * @property mixed $payment_method TEXT
 * @property mixed $transfers TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $transfer_duration INTEGER
 */
class FareAttributeRow extends Row
{
    protected $cols = [
        'fare_id' => null,
        'price' => null,
        'currency_type' => null,
        'payment_method' => null,
        'transfers' => null,
        'agency_id' => null,
        'transfer_duration' => null,
    ];
}
