<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\FareAttribute;

/**
 * @property mixed $fare_id TEXT
 * @property mixed $price REAL
 * @property mixed $currency_type TEXT
 * @property mixed $payment_method TEXT
 * @property mixed $transfers TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $transfer_duration INTEGER
 */
trait FareAttributeFields
{
}
