<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Translation;

use Atlas\Table\Row;

/**
 * @property mixed $table_name TEXT
 * @property mixed $field_name TEXT
 * @property mixed $language TEXT
 * @property mixed $translation TEXT
 * @property mixed $record_id TEXT
 * @property mixed $record_sub_id TEXT
 * @property mixed $field_value TEXT
 */
class TranslationRow extends Row
{
    protected $cols = [
        'table_name' => null,
        'field_name' => null,
        'language' => null,
        'translation' => null,
        'record_id' => null,
        'record_sub_id' => null,
        'field_value' => null,
    ];
}
