<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Translation;

/**
 * @property mixed $table_name TEXT
 * @property mixed $field_name TEXT
 * @property mixed $language TEXT
 * @property mixed $translation TEXT
 * @property mixed $record_id TEXT
 * @property mixed $record_sub_id TEXT
 * @property mixed $field_value TEXT
 */
trait TranslationFields
{
}
