<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\FareAttribute;

/**
 * @property mixed $fare_id TEXT
 * @property mixed $price TEXT
 * @property mixed $currency_type TEXT
 * @property mixed $payment_method TEXT
 * @property mixed $transfers TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $transfer_duration TEXT
 */
trait FareAttributeFields
{
}
