<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\FareAttribute;

use Atlas\Table\Table;

/**
 * @method FareAttributeRow|null fetchRow($primaryVal)
 * @method FareAttributeRow[] fetchRows(array $primaryVals)
 * @method FareAttributeTableSelect select(array $whereEquals = [])
 * @method FareAttributeRow newRow(array $cols = [])
 * @method FareAttributeRow newSelectedRow(array $cols)
 */
class FareAttributeTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'fare_attributes';

    const COLUMNS = [
        'fare_id' => array (
  'name' => 'fare_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'price' => array (
  'name' => 'price',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'currency_type' => array (
  'name' => 'currency_type',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'payment_method' => array (
  'name' => 'payment_method',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'transfers' => array (
  'name' => 'transfers',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'agency_id' => array (
  'name' => 'agency_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'transfer_duration' => array (
  'name' => 'transfer_duration',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'fare_id',
        'price',
        'currency_type',
        'payment_method',
        'transfers',
        'agency_id',
        'transfer_duration',
    ];

    const COLUMN_DEFAULTS = [
        'fare_id' => null,
        'price' => null,
        'currency_type' => null,
        'payment_method' => null,
        'transfers' => null,
        'agency_id' => null,
        'transfer_duration' => null,
    ];

    const PRIMARY_KEY = [
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
