<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\StopTime;

/**
 * @property mixed $trip_id TEXT
 * @property mixed $arrival_time TEXT
 * @property mixed $departure_time TEXT
 * @property mixed $stop_id TEXT
 * @property mixed $stop_sequence TEXT
 * @property mixed $stop_headsign TEXT
 * @property mixed $pickup_type TEXT
 * @property mixed $drop_off_type TEXT
 * @property mixed $shape_dist_traveled TEXT
 * @property mixed $timepoint TEXT
 */
trait StopTimeFields
{
}
