<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Attribution;

/**
 * @property mixed $attribution_id TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $trip_id TEXT
 * @property mixed $organization_name TEXT
 * @property mixed $is_producer TEXT
 * @property mixed $is_operator TEXT
 * @property mixed $is_authority TEXT
 * @property mixed $attribution_url TEXT
 * @property mixed $attribution_email TEXT
 * @property mixed $attribution_phone TEXT
 */
trait AttributionFields
{
}
