<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Level;

use Atlas\Table\Table;

/**
 * @method LevelRow|null fetchRow($primaryVal)
 * @method LevelRow[] fetchRows(array $primaryVals)
 * @method LevelTableSelect select(array $whereEquals = [])
 * @method LevelRow newRow(array $cols = [])
 * @method LevelRow newSelectedRow(array $cols)
 */
class LevelTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'levels';

    const COLUMNS = [
        'level_id' => array (
  'name' => 'level_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'level_index' => array (
  'name' => 'level_index',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'level_name' => array (
  'name' => 'level_name',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'level_id',
        'level_index',
        'level_name',
    ];

    const COLUMN_DEFAULTS = [
        'level_id' => null,
        'level_index' => null,
        'level_name' => null,
    ];

    const PRIMARY_KEY = [
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
