<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Frequency;

use Atlas\Table\Row;

/**
 * @property mixed $trip_id TEXT
 * @property mixed $start_time TEXT
 * @property mixed $end_time TEXT
 * @property mixed $headway_secs INTEGER
 * @property mixed $exact_times TEXT
 */
class FrequencyRow extends Row
{
    protected $cols = [
        'trip_id' => null,
        'start_time' => null,
        'end_time' => null,
        'headway_secs' => null,
        'exact_times' => null,
    ];
}
