<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Frequency;

/**
 * @property mixed $trip_id TEXT
 * @property mixed $start_time TEXT
 * @property mixed $end_time TEXT
 * @property mixed $headway_secs INTEGER
 * @property mixed $exact_times INTEGER
 */
trait FrequencyFields
{
}
