<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Route;

/**
 * @property mixed $route_id TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $route_short_name TEXT
 * @property mixed $route_long_name TEXT
 * @property mixed $route_desc TEXT
 * @property mixed $route_type TEXT
 * @property mixed $route_url TEXT
 * @property mixed $route_color TEXT
 * @property mixed $route_text_color TEXT
 * @property mixed $route_sort_order TEXT
 */
trait RouteFields
{
}
