<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Route;

use Atlas\Table\Row;

/**
 * @property mixed $route_id TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $route_short_name TEXT
 * @property mixed $route_long_name TEXT
 * @property mixed $route_desc TEXT
 * @property mixed $route_type TEXT
 * @property mixed $route_url TEXT
 * @property mixed $route_color TEXT
 * @property mixed $route_text_color TEXT
 * @property mixed $route_sort_order INTEGER
 */
class RouteRow extends Row
{
    protected $cols = [
        'route_id' => null,
        'agency_id' => null,
        'route_short_name' => null,
        'route_long_name' => null,
        'route_desc' => null,
        'route_type' => null,
        'route_url' => null,
        'route_color' => null,
        'route_text_color' => null,
        'route_sort_order' => 1,
    ];
}
