<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\Agency;

use Atlas\Table\Row;

/**
 * @property mixed $agency_id TEXT
 * @property mixed $agency_name TEXT
 * @property mixed $agency_url TEXT
 * @property mixed $agency_timezone TEXT
 * @property mixed $agency_lang TEXT
 * @property mixed $agency_phone TEXT
 * @property mixed $agency_fare_url TEXT
 * @property mixed $agency_email TEXT
 */
class AgencyRow extends Row
{
    protected $cols = [
        'agency_id' => null,
        'agency_name' => null,
        'agency_url' => null,
        'agency_timezone' => null,
        'agency_lang' => null,
        'agency_phone' => null,
        'agency_fare_url' => null,
        'agency_email' => null,
    ];
}
