<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeVehiclePosition;

use Atlas\Table\Row;

/**
 * @property mixed $vehicle_id TEXT NOT NULL
 * @property mixed $timestamp INTEGER
 * @property mixed $vehicle_label TEXT
 * @property mixed $vehicle_license_plate TEXT
 * @property mixed $position_lat REAL
 * @property mixed $position_lon REAL
 * @property mixed $position_bearing REAL
 * @property mixed $position_odometer REAL
 * @property mixed $position_speed REAL
 * @property mixed $congestion_level TEXT
 * @property mixed $occupancy_status TEXT
 * @property mixed $stop_status TEXT
 */
class RealtimeVehiclePositionRow extends Row
{
    protected $cols = [
        'vehicle_id' => null,
        'timestamp' => null,
        'vehicle_label' => null,
        'vehicle_license_plate' => null,
        'position_lat' => null,
        'position_lon' => null,
        'position_bearing' => null,
        'position_odometer' => null,
        'position_speed' => null,
        'congestion_level' => null,
        'occupancy_status' => null,
        'stop_status' => null,
    ];
}
