<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\RealtimeVehiclePosition;

/**
 * @property mixed $vehicle_id TEXT NOT NULL
 * @property mixed $timestamp INTEGER
 * @property mixed $vehicle_label TEXT
 * @property mixed $vehicle_license_plate TEXT
 * @property mixed $position_lat REAL
 * @property mixed $position_lon REAL
 * @property mixed $position_bearing REAL
 * @property mixed $position_speed REAL
 */
trait RealtimeVehiclePositionFields
{
}
