<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\FeedInfo;

use Atlas\Table\Table;

/**
 * @method FeedInfoRow|null fetchRow($primaryVal)
 * @method FeedInfoRow[] fetchRows(array $primaryVals)
 * @method FeedInfoTableSelect select(array $whereEquals = [])
 * @method FeedInfoRow newRow(array $cols = [])
 * @method FeedInfoRow newSelectedRow(array $cols)
 */
class FeedInfoTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'feed_info';

    const COLUMNS = [
        'feed_publisher_name' => array (
  'name' => 'feed_publisher_name',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_publisher_url' => array (
  'name' => 'feed_publisher_url',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_lang' => array (
  'name' => 'feed_lang',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_start_date' => array (
  'name' => 'feed_start_date',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_end_date' => array (
  'name' => 'feed_end_date',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_version' => array (
  'name' => 'feed_version',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_contact_email' => array (
  'name' => 'feed_contact_email',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'feed_contact_url' => array (
  'name' => 'feed_contact_url',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'feed_publisher_name',
        'feed_publisher_url',
        'feed_lang',
        'feed_start_date',
        'feed_end_date',
        'feed_version',
        'feed_contact_email',
        'feed_contact_url',
    ];

    const COLUMN_DEFAULTS = [
        'feed_publisher_name' => null,
        'feed_publisher_url' => null,
        'feed_lang' => null,
        'feed_start_date' => null,
        'feed_end_date' => null,
        'feed_version' => null,
        'feed_contact_email' => null,
        'feed_contact_url' => null,
    ];

    const PRIMARY_KEY = [
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
