<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\FeedInfo;

use Atlas\Table\Row;

/**
 * @property mixed $feed_publisher_name TEXT
 * @property mixed $feed_publisher_url TEXT
 * @property mixed $feed_lang TEXT
 * @property mixed $feed_start_date TEXT
 * @property mixed $feed_end_date TEXT
 * @property mixed $feed_version TEXT
 * @property mixed $feed_contact_email TEXT
 * @property mixed $feed_contact_url TEXT
 */
class FeedInfoRow extends Row
{
    protected $cols = [
        'feed_publisher_name' => null,
        'feed_publisher_url' => null,
        'feed_lang' => null,
        'feed_start_date' => null,
        'feed_end_date' => null,
        'feed_version' => null,
        'feed_contact_email' => null,
        'feed_contact_url' => null,
    ];
}
