<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\StopTime;

/**
 * @property mixed $trip_id TEXT
 * @property mixed $arrival_time TEXT
 * @property mixed $departure_time TEXT
 * @property mixed $stop_id TEXT
 * @property mixed $stop_sequence INTEGER
 * @property mixed $stop_headsign TEXT
 * @property mixed $pickup_type TEXT
 * @property mixed $drop_off_type TEXT
 * @property mixed $shape_dist_traveled REAL
 * @property mixed $timepoint TEXT
 * @property null|false|\App\Google\Transit\Stop\StopRecord $stop
 */
trait StopTimeFields
{
}
