<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Agency;

/**
 * @property mixed $agency_id TEXT
 * @property mixed $agency_name TEXT
 * @property mixed $agency_url TEXT
 * @property mixed $agency_timezone TEXT
 * @property mixed $agency_lang TEXT
 * @property mixed $agency_phone TEXT
 * @property mixed $agency_fare_url TEXT
 * @property mixed $agency_email TEXT
 */
trait AgencyFields
{
}
