<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\RealtimeAlert;

/**
 * @property mixed $alert_id INTEGER
 * @property mixed $alert_cause TEXT
 * @property mixed $alert_effect TEXT
 * @property mixed $alert_url TEXT
 * @property mixed $alert_header_text TEXT
 * @property mixed $alert_description_text TEXT
 */
trait RealtimeAlertFields
{
}
