<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeAlert;

use Atlas\Table\Table;

/**
 * @method RealtimeAlertRow|null fetchRow($primaryVal)
 * @method RealtimeAlertRow[] fetchRows(array $primaryVals)
 * @method RealtimeAlertTableSelect select(array $whereEquals = [])
 * @method RealtimeAlertRow newRow(array $cols = [])
 * @method RealtimeAlertRow newSelectedRow(array $cols)
 */
class RealtimeAlertTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'realtime_alerts';

    const COLUMNS = [
        'alert_id' => array (
  'name' => 'alert_id',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'alert_cause' => array (
  'name' => 'alert_cause',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'alert_effect' => array (
  'name' => 'alert_effect',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'alert_url' => array (
  'name' => 'alert_url',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'alert_header_text' => array (
  'name' => 'alert_header_text',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'alert_description_text' => array (
  'name' => 'alert_description_text',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'alert_id',
        'alert_cause',
        'alert_effect',
        'alert_url',
        'alert_header_text',
        'alert_description_text',
    ];

    const COLUMN_DEFAULTS = [
        'alert_id' => null,
        'alert_cause' => null,
        'alert_effect' => null,
        'alert_url' => null,
        'alert_header_text' => null,
        'alert_description_text' => null,
    ];

    const PRIMARY_KEY = [
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
