<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Stop;

use Atlas\Table\Row;

/**
 * @property mixed $stop_id TEXT
 * @property mixed $stop_code TEXT
 * @property mixed $stop_name TEXT
 * @property mixed $stop_desc TEXT
 * @property mixed $stop_lat TEXT
 * @property mixed $stop_lon TEXT
 * @property mixed $zone_id TEXT
 * @property mixed $stop_url TEXT
 * @property mixed $location_type TEXT
 * @property mixed $parent_station TEXT
 * @property mixed $stop_timezone TEXT
 * @property mixed $wheelchair_boarding TEXT
 * @property mixed $level_id TEXT
 * @property mixed $platform_code TEXT
 */
class StopRow extends Row
{
    protected $cols = [
        'stop_id' => null,
        'stop_code' => null,
        'stop_name' => null,
        'stop_desc' => null,
        'stop_lat' => null,
        'stop_lon' => null,
        'zone_id' => null,
        'stop_url' => null,
        'location_type' => null,
        'parent_station' => null,
        'stop_timezone' => null,
        'wheelchair_boarding' => null,
        'level_id' => null,
        'platform_code' => null,
    ];
}
