<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Stop;

/**
 * @property mixed $stop_id TEXT
 * @property mixed $stop_code TEXT
 * @property mixed $stop_name TEXT
 * @property mixed $stop_desc TEXT
 * @property mixed $stop_lat REAL
 * @property mixed $stop_lon REAL
 * @property mixed $zone_id TEXT
 * @property mixed $stop_url TEXT
 * @property mixed $location_type TEXT
 * @property mixed $parent_station TEXT
 * @property mixed $stop_timezone TEXT
 * @property mixed $wheelchair_boarding TEXT
 * @property mixed $level_id TEXT
 * @property mixed $platform_code TEXT
 * @property null|\App\Data\StopTime\StopTimeRecordSet $stop_times
 * @property null|\App\Data\Transfer\TransferRecordSet $transfers
 * @property null|false|\App\Data\Level\LevelRecord $level
 */
trait StopFields
{
}
