<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeTripUpdate;

/**
 * @property mixed $trip_update_id INTEGER NOT NULL
 * @property mixed $trip_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $trip_start_date TEXT
 * @property mixed $trip_start_time TEXT
 * @property mixed $vehicle_id TEXT
 * @property mixed $schedule_relationship TEXT
 */
trait RealtimeTripUpdateFields
{
}
