<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeTripUpdate;

use Atlas\Table\Row;

/**
 * @property mixed $trip_update_id INTEGER NOT NULL
 * @property mixed $timestamp INTEGER
 * @property mixed $trip_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $trip_start_date TEXT
 * @property mixed $trip_start_time TEXT
 * @property mixed $vehicle_id TEXT
 * @property mixed $schedule_relationship TEXT
 */
class RealtimeTripUpdateRow extends Row
{
    protected $cols = [
        'trip_update_id' => null,
        'timestamp' => null,
        'trip_id' => null,
        'route_id' => null,
        'trip_start_date' => null,
        'trip_start_time' => null,
        'vehicle_id' => null,
        'schedule_relationship' => null,
    ];
}
