<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\RealtimeTripUpdate;

use Atlas\Table\Table;

/**
 * @method RealtimeTripUpdateRow|null fetchRow($primaryVal)
 * @method RealtimeTripUpdateRow[] fetchRows(array $primaryVals)
 * @method RealtimeTripUpdateTableSelect select(array $whereEquals = [])
 * @method RealtimeTripUpdateRow newRow(array $cols = [])
 * @method RealtimeTripUpdateRow newSelectedRow(array $cols)
 */
class RealtimeTripUpdateTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'realtime_trip_updates';

    const COLUMNS = [
        'trip_update_id' => array (
  'name' => 'trip_update_id',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'trip_id' => array (
  'name' => 'trip_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'route_id' => array (
  'name' => 'route_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'trip_start_date' => array (
  'name' => 'trip_start_date',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'trip_start_time' => array (
  'name' => 'trip_start_time',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'vehicle_id' => array (
  'name' => 'vehicle_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'schedule_relationship' => array (
  'name' => 'schedule_relationship',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'trip_update_id',
        'trip_id',
        'route_id',
        'trip_start_date',
        'trip_start_time',
        'vehicle_id',
        'schedule_relationship',
    ];

    const COLUMN_DEFAULTS = [
        'trip_update_id' => null,
        'trip_id' => null,
        'route_id' => null,
        'trip_start_date' => null,
        'trip_start_time' => null,
        'vehicle_id' => null,
        'schedule_relationship' => null,
    ];

    const PRIMARY_KEY = [
        'trip_update_id',
    ];

    const AUTOINC_COLUMN = 'trip_update_id';

    const AUTOINC_SEQUENCE = null;
}
