<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\Attribution;

use Atlas\Table\Row;

/**
 * @property mixed $attribution_id TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $trip_id TEXT
 * @property mixed $organization_name TEXT
 * @property mixed $is_producer TEXT
 * @property mixed $is_operator TEXT
 * @property mixed $is_authority TEXT
 * @property mixed $attribution_url TEXT
 * @property mixed $attribution_email TEXT
 * @property mixed $attribution_phone TEXT
 */
class AttributionRow extends Row
{
    protected $cols = [
        'attribution_id' => null,
        'agency_id' => null,
        'route_id' => null,
        'trip_id' => null,
        'organization_name' => null,
        'is_producer' => null,
        'is_operator' => null,
        'is_authority' => null,
        'attribution_url' => null,
        'attribution_email' => null,
        'attribution_phone' => null,
    ];
}
