<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\FeedInfo;

/**
 * @property mixed $feed_publisher_name TEXT
 * @property mixed $feed_publisher_url TEXT
 * @property mixed $feed_lang TEXT
 * @property mixed $feed_start_date TEXT
 * @property mixed $feed_end_date TEXT
 * @property mixed $feed_version TEXT
 * @property mixed $feed_contact_email TEXT
 * @property mixed $feed_contact_url TEXT
 */
trait FeedInfoFields
{
}
