<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\Shape;

/**
 * @property mixed $shape_id TEXT
 * @property mixed $shape_pt_lat REAL
 * @property mixed $shape_pt_lon REAL
 * @property mixed $shape_pt_sequence INTEGER
 * @property mixed $shape_dist_traveled REAL
 */
trait ShapeFields
{
}
