<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Transfer;

use Atlas\Table\Row;

/**
 * @property mixed $from_stop_id 
 * @property mixed $to_stop_id 
 * @property mixed $transfer_type 
 * @property mixed $min_transfer_time
 */
class TransferRow extends Row
{
    protected $cols = [
        'from_stop_id' => null,
        'to_stop_id' => null,
        'transfer_type' => null,
        'min_transfer_time' => null,
    ];
}
