<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Transfer;

/**
 * @property mixed $from_stop_id 
 * @property mixed $to_stop_id 
 * @property mixed $transfer_type 
 * @property mixed $min_transfer_time
 */
trait TransferFields
{
}
