<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Transfer;

/**
 * @property mixed $from_stop_id 
 * @property mixed $to_stop_id 
 * @property mixed $transfer_type 
 * @property mixed $min_transfer_time
 */
trait TransferFields
{
}
