<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeStopTimeUpdate;

/**
 * @property mixed $_id INTEGER NOT NULL
 * @property mixed $trip_update_id INTEGER
 * @property mixed $stop_id TEXT
 * @property mixed $stop_sequence INTEGER
 * @property mixed $arrival_delay INTEGER
 * @property mixed $arrival_time INTEGER
 * @property mixed $arrival_uncertainty INTEGER
 * @property mixed $departure_delay INTEGER
 * @property mixed $departure_time INTEGER
 * @property mixed $departure_uncertainty INTEGER
 * @property mixed $schedule_relationship TEXT
 */
trait RealtimeStopTimeUpdateFields
{
}
