<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\RealtimeStopTimeUpdate;

/**
 * @property mixed $trip_update_id INTEGER
 * @property mixed $stop_id TEXT
 * @property mixed $stop_sequence INTEGER
 * @property mixed $arrival_delay INTEGER
 * @property mixed $arrival_time TEXT
 * @property mixed $arrival_uncertainty TEXT
 * @property mixed $depature_delay INTEGER
 * @property mixed $departure_time TEXT
 * @property mixed $departure_uncertainty TEXT
 * @property mixed $schedule_relationship TEXT
 */
trait RealtimeStopTimeUpdateFields
{
}
