<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeStopTimeUpdate;

use Atlas\Table\Row;

/**
 * @property mixed $trip_update_id INTEGER
 * @property mixed $stop_id TEXT
 * @property mixed $stop_sequence INTEGER
 * @property mixed $arrival_delay INTEGER
 * @property mixed $arrival_time INTEGER
 * @property mixed $arrival_uncertainty INTEGER
 * @property mixed $depature_delay INTEGER
 * @property mixed $departure_time INTEGER
 * @property mixed $departure_uncertainty INTEGER
 * @property mixed $schedule_relationship TEXT
 */
class RealtimeStopTimeUpdateRow extends Row
{
    protected $cols = [
        'trip_update_id' => null,
        'stop_id' => null,
        'stop_sequence' => null,
        'arrival_delay' => null,
        'arrival_time' => null,
        'arrival_uncertainty' => null,
        'depature_delay' => null,
        'departure_time' => null,
        'departure_uncertainty' => null,
        'schedule_relationship' => null,
    ];
}
