<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Shape;

use Atlas\Table\Row;

/**
 * @property mixed $shape_id TEXT
 * @property mixed $shape_pt_lat TEXT
 * @property mixed $shape_pt_lon TEXT
 * @property mixed $shape_pt_sequence TEXT
 * @property mixed $shape_dist_traveled TEXT
 */
class ShapeRow extends Row
{
    protected $cols = [
        'shape_id' => null,
        'shape_pt_lat' => null,
        'shape_pt_lon' => null,
        'shape_pt_sequence' => null,
        'shape_dist_traveled' => null,
    ];
}
