<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Shape;

/**
 * @property mixed $shape_id TEXT
 * @property mixed $shape_pt_lat TEXT
 * @property mixed $shape_pt_lon TEXT
 * @property mixed $shape_pt_sequence TEXT
 * @property mixed $shape_dist_traveled TEXT
 */
trait ShapeFields
{
}
