<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\CalendarDate;

use Atlas\Table\Table;

/**
 * @method CalendarDateRow|null fetchRow($primaryVal)
 * @method CalendarDateRow[] fetchRows(array $primaryVals)
 * @method CalendarDateTableSelect select(array $whereEquals = [])
 * @method CalendarDateRow newRow(array $cols = [])
 * @method CalendarDateRow newSelectedRow(array $cols)
 */
class CalendarDateTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'calendar_dates';

    const COLUMNS = [
        'service_id' => array (
  'name' => 'service_id',
  'type' => '',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'date' => array (
  'name' => 'date',
  'type' => '',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'exception_type' => array (
  'name' => 'exception_type',
  'type' => '',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'service_id',
        'date',
        'exception_type',
    ];

    const COLUMN_DEFAULTS = [
        'service_id' => null,
        'date' => null,
        'exception_type' => null,
    ];

    const PRIMARY_KEY = [
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
