<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\CalendarDate;

use Atlas\Table\Row;

/**
 * @property mixed $service_id 
 * @property mixed $date 
 * @property mixed $exception_type
 */
class CalendarDateRow extends Row
{
    protected $cols = [
        'service_id' => null,
        'date' => null,
        'exception_type' => null,
    ];
}
