<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\CalendarDate;

/**
 * @property mixed $service_id 
 * @property mixed $date 
 * @property mixed $exception_type
 */
trait CalendarDateFields
{
}
