<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\CalendarDate;

/**
 * @property mixed $service_id TEXT
 * @property mixed $date TEXT
 * @property mixed $exception_type TEXT
 */
trait CalendarDateFields
{
}
