<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\CalendarDate;

use Atlas\Table\Row;

/**
 * @property mixed $service_id TEXT
 * @property mixed $date TEXT
 * @property mixed $exception_type TEXT
 */
class CalendarDateRow extends Row
{
    protected $cols = [
        'service_id' => null,
        'date' => null,
        'exception_type' => null,
    ];
}
