<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Route;

/**
 * @property mixed $route_id TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $route_short_name TEXT
 * @property mixed $route_long_name TEXT
 * @property mixed $route_desc TEXT
 * @property mixed $route_type TEXT
 * @property mixed $route_url TEXT
 * @property mixed $route_color TEXT
 * @property mixed $route_text_color TEXT
 * @property mixed $route_sort_order INTEGER
 */
trait RouteFields
{
}
