<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeAlertTimerange;

use Atlas\Table\Table;

/**
 * @method RealtimeAlertTimerangeRow|null fetchRow($primaryVal)
 * @method RealtimeAlertTimerangeRow[] fetchRows(array $primaryVals)
 * @method RealtimeAlertTimerangeTableSelect select(array $whereEquals = [])
 * @method RealtimeAlertTimerangeRow newRow(array $cols = [])
 * @method RealtimeAlertTimerangeRow newSelectedRow(array $cols)
 */
class RealtimeAlertTimerangeTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'realtime_alert_timeranges';

    const COLUMNS = [
        '_id' => array (
  'name' => '_id',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'alert_id' => array (
  'name' => 'alert_id',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'start_time' => array (
  'name' => 'start_time',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'end_time' => array (
  'name' => 'end_time',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        '_id',
        'alert_id',
        'start_time',
        'end_time',
    ];

    const COLUMN_DEFAULTS = [
        '_id' => null,
        'alert_id' => null,
        'start_time' => null,
        'end_time' => null,
    ];

    const PRIMARY_KEY = [
        '_id',
    ];

    const AUTOINC_COLUMN = '_id';

    const AUTOINC_SEQUENCE = null;
}
