<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Transfer;

/**
 * @property mixed $from_stop_id TEXT
 * @property mixed $to_stop_id TEXT
 * @property mixed $transfer_type TEXT
 * @property mixed $min_transfer_time INTEGER
 */
trait TransferFields
{
}
