<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Frequency;

/**
 * @property mixed $trip_id TEXT
 * @property mixed $start_time TEXT
 * @property mixed $end_time TEXT
 * @property mixed $headway_secs INTEGER
 * @property mixed $exact_times TEXT
 */
trait FrequencyFields
{
}
