<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Frequency;

use Atlas\Table\Table;

/**
 * @method FrequencyRow|null fetchRow($primaryVal)
 * @method FrequencyRow[] fetchRows(array $primaryVals)
 * @method FrequencyTableSelect select(array $whereEquals = [])
 * @method FrequencyRow newRow(array $cols = [])
 * @method FrequencyRow newSelectedRow(array $cols)
 */
class FrequencyTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'frequencies';

    const COLUMNS = [
        'trip_id' => array (
  'name' => 'trip_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'start_time' => array (
  'name' => 'start_time',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'end_time' => array (
  'name' => 'end_time',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'headway_secs' => array (
  'name' => 'headway_secs',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'exact_times' => array (
  'name' => 'exact_times',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'trip_id',
        'start_time',
        'end_time',
        'headway_secs',
        'exact_times',
    ];

    const COLUMN_DEFAULTS = [
        'trip_id' => null,
        'start_time' => null,
        'end_time' => null,
        'headway_secs' => null,
        'exact_times' => null,
    ];

    const PRIMARY_KEY = [
        'trip_id',
        'start_time',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
