<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Pathway;

use Atlas\Table\Table;

/**
 * @method PathwayRow|null fetchRow($primaryVal)
 * @method PathwayRow[] fetchRows(array $primaryVals)
 * @method PathwayTableSelect select(array $whereEquals = [])
 * @method PathwayRow newRow(array $cols = [])
 * @method PathwayRow newSelectedRow(array $cols)
 */
class PathwayTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'pathways';

    const COLUMNS = [
        'pathway_id' => array (
  'name' => 'pathway_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'from_stop_id' => array (
  'name' => 'from_stop_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'to_stop_id' => array (
  'name' => 'to_stop_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'pathway_mode' => array (
  'name' => 'pathway_mode',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'is_bidirectional' => array (
  'name' => 'is_bidirectional',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'length' => array (
  'name' => 'length',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'traversal_time' => array (
  'name' => 'traversal_time',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'stair_count' => array (
  'name' => 'stair_count',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'max_slope' => array (
  'name' => 'max_slope',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'min_width' => array (
  'name' => 'min_width',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'signposted_as' => array (
  'name' => 'signposted_as',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'reversed_signposted_as' => array (
  'name' => 'reversed_signposted_as',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'pathway_id',
        'from_stop_id',
        'to_stop_id',
        'pathway_mode',
        'is_bidirectional',
        'length',
        'traversal_time',
        'stair_count',
        'max_slope',
        'min_width',
        'signposted_as',
        'reversed_signposted_as',
    ];

    const COLUMN_DEFAULTS = [
        'pathway_id' => null,
        'from_stop_id' => null,
        'to_stop_id' => null,
        'pathway_mode' => null,
        'is_bidirectional' => null,
        'length' => null,
        'traversal_time' => null,
        'stair_count' => null,
        'max_slope' => null,
        'min_width' => null,
        'signposted_as' => null,
        'reversed_signposted_as' => null,
    ];

    const PRIMARY_KEY = [
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
