<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Pathway;

/**
 * @property mixed $pathway_id TEXT
 * @property mixed $from_stop_id TEXT
 * @property mixed $to_stop_id TEXT
 * @property mixed $pathway_mode TEXT
 * @property mixed $is_bidirectional TEXT
 * @property mixed $length REAL
 * @property mixed $traversal_time INTEGER
 * @property mixed $stair_count INTEGER
 * @property mixed $max_slope REAL
 * @property mixed $min_width REAL
 * @property mixed $signposted_as TEXT
 * @property mixed $reversed_signposted_as TEXT
 */
trait PathwayFields
{
}
