<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Pathway;

use Atlas\Table\Row;

/**
 * @property mixed $pathway_id TEXT
 * @property mixed $from_stop_id TEXT
 * @property mixed $to_stop_id TEXT
 * @property mixed $pathway_mode TEXT
 * @property mixed $is_bidirectional TEXT
 * @property mixed $length TEXT
 * @property mixed $traversal_time TEXT
 * @property mixed $stair_count TEXT
 * @property mixed $max_slope TEXT
 * @property mixed $min_width TEXT
 * @property mixed $signposted_as TEXT
 * @property mixed $reversed_signposted_as TEXT
 */
class PathwayRow extends Row
{
    protected $cols = [
        'pathway_id' => null,
        'from_stop_id' => null,
        'to_stop_id' => null,
        'pathway_mode' => null,
        'is_bidirectional' => null,
        'length' => null,
        'traversal_time' => null,
        'stair_count' => null,
        'max_slope' => null,
        'min_width' => null,
        'signposted_as' => null,
        'reversed_signposted_as' => null,
    ];
}
