<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Google\Transit\Translation;

use Atlas\Table\Table;

/**
 * @method TranslationRow|null fetchRow($primaryVal)
 * @method TranslationRow[] fetchRows(array $primaryVals)
 * @method TranslationTableSelect select(array $whereEquals = [])
 * @method TranslationRow newRow(array $cols = [])
 * @method TranslationRow newSelectedRow(array $cols)
 */
class TranslationTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'translations';

    const COLUMNS = [
        'table_name' => array (
  'name' => 'table_name',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'field_name' => array (
  'name' => 'field_name',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'language' => array (
  'name' => 'language',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'translation' => array (
  'name' => 'translation',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'record_id' => array (
  'name' => 'record_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'record_sub_id' => array (
  'name' => 'record_sub_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => true,
  'options' => NULL,
),
        'field_value' => array (
  'name' => 'field_value',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        'table_name',
        'field_name',
        'language',
        'translation',
        'record_id',
        'record_sub_id',
        'field_value',
    ];

    const COLUMN_DEFAULTS = [
        'table_name' => null,
        'field_name' => null,
        'language' => null,
        'translation' => null,
        'record_id' => null,
        'record_sub_id' => null,
        'field_value' => null,
    ];

    const PRIMARY_KEY = [
        'table_name',
        'field_name',
        'language',
        'record_id',
        'record_sub_id',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
