<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Trip;

/**
 * @property mixed $route_id TEXT
 * @property mixed $service_id TEXT
 * @property mixed $trip_id TEXT
 * @property mixed $trip_headsign TEXT
 * @property mixed $trip_short_name TEXT
 * @property mixed $direction_id TEXT
 * @property mixed $block_id TEXT
 * @property mixed $shape_id TEXT
 * @property mixed $wheelchair_accessible TEXT
 * @property mixed $bikes_allowed TEXT
 * @property null|false|\App\Data\Route\RouteRecord $route
 * @property null|false|\App\Data\Calendar\CalendarRecord $service
 * @property null|\App\Data\StopTime\StopTimeRecordSet $stop_times
 * @property null|\App\Data\Frequency\FrequencyRecordSet $frequencies
 * @property null|\App\Data\Shape\ShapeRecordSet $shape
 * @property null|false|\App\Data\Calendar\CalendarRecord $calendar
 */
trait TripFields
{
}
