<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Trip;

use Atlas\Table\Row;

/**
 * @property mixed $route_id TEXT
 * @property mixed $service_id TEXT
 * @property mixed $trip_id TEXT
 * @property mixed $trip_headsign TEXT
 * @property mixed $trip_short_name TEXT
 * @property mixed $direction_id TEXT
 * @property mixed $block_id TEXT
 * @property mixed $shape_id TEXT
 * @property mixed $wheelchair_accessible TEXT
 * @property mixed $bikes_allowed TEXT
 */
class TripRow extends Row
{
    protected $cols = [
        'route_id' => null,
        'service_id' => null,
        'trip_id' => null,
        'trip_headsign' => null,
        'trip_short_name' => null,
        'direction_id' => null,
        'block_id' => null,
        'shape_id' => null,
        'wheelchair_accessible' => null,
        'bikes_allowed' => null,
    ];
}
