<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Calendar;

use Atlas\Table\Row;

/**
 * @property mixed $service_id 
 * @property mixed $monday 
 * @property mixed $tuesday 
 * @property mixed $wednesday 
 * @property mixed $thursday 
 * @property mixed $friday 
 * @property mixed $saturday 
 * @property mixed $sunday 
 * @property mixed $start_date 
 * @property mixed $end_date
 */
class CalendarRow extends Row
{
    protected $cols = [
        'service_id' => null,
        'monday' => null,
        'tuesday' => null,
        'wednesday' => null,
        'thursday' => null,
        'friday' => null,
        'saturday' => null,
        'sunday' => null,
        'start_date' => null,
        'end_date' => null,
    ];
}
