<?php
/**
 * This file remains to the GTFS-REST-API - Copyright (c) 2020.
 *
 * @author Sebastian Knopf
 * @license http://opensource.org/licenses/MIT MIT
 */

/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Data\Calendar;

/**
 * @property mixed $service_id 
 * @property mixed $monday 
 * @property mixed $tuesday 
 * @property mixed $wednesday 
 * @property mixed $thursday 
 * @property mixed $friday 
 * @property mixed $saturday 
 * @property mixed $sunday 
 * @property mixed $start_date 
 * @property mixed $end_date
 */
trait CalendarFields
{
}
