<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeAlertEntity;

use Atlas\Table\Table;

/**
 * @method RealtimeAlertEntityRow|null fetchRow($primaryVal)
 * @method RealtimeAlertEntityRow[] fetchRows(array $primaryVals)
 * @method RealtimeAlertEntityTableSelect select(array $whereEquals = [])
 * @method RealtimeAlertEntityRow newRow(array $cols = [])
 * @method RealtimeAlertEntityRow newSelectedRow(array $cols)
 */
class RealtimeAlertEntityTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'realtime_alert_entities';

    const COLUMNS = [
        '_id' => array (
  'name' => '_id',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
  'options' => NULL,
),
        'alert_id' => array (
  'name' => 'alert_id',
  'type' => 'INTEGER',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'stop_id' => array (
  'name' => 'stop_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'agency_id' => array (
  'name' => 'agency_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'route_id' => array (
  'name' => 'route_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'trip_id' => array (
  'name' => 'trip_id',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'trip_start_date' => array (
  'name' => 'trip_start_date',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'trip_start_time' => array (
  'name' => 'trip_start_time',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
        'route_type' => array (
  'name' => 'route_type',
  'type' => 'TEXT',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
  'options' => NULL,
),
    ];

    const COLUMN_NAMES = [
        '_id',
        'alert_id',
        'stop_id',
        'agency_id',
        'route_id',
        'trip_id',
        'trip_start_date',
        'trip_start_time',
        'route_type',
    ];

    const COLUMN_DEFAULTS = [
        '_id' => null,
        'alert_id' => null,
        'stop_id' => null,
        'agency_id' => null,
        'route_id' => null,
        'trip_id' => null,
        'trip_start_date' => null,
        'trip_start_time' => null,
        'route_type' => null,
    ];

    const PRIMARY_KEY = [
        '_id',
    ];

    const AUTOINC_COLUMN = '_id';

    const AUTOINC_SEQUENCE = null;
}
