<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\Google\Transit\RealtimeAlertEntity;

/**
 * @property mixed $alert_id INTEGER NOT NULL
 * @property mixed $stop_id TEXT
 * @property mixed $agency_id TEXT
 * @property mixed $route_id TEXT
 * @property mixed $trip_id TEXT
 * @property mixed $trip_start_date TEXT
 * @property mixed $trip_start_time TEXT
 * @property mixed $route_type TEXT
 */
trait RealtimeAlertEntityFields
{
}
